[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.17'

[fmt]
line_length = 121
multiline_func_header = 'params_first'
